services:
  postgres:
    image: 'postgres:latest'
    container_name: Bank
    environment:
      - 'POSTGRES_DB=Bank'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'